name: lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nebularg/actions-luacheck@v1.1.0
        with:
          files: 'lua/'
          config: 'https://raw.githubusercontent.com/NTBBloodbath/rest.nvim/main/.luacheckrc'
          annotate: 'error'
