name: lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  selene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup and run selene
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: "lua/"
