name: Luarocks release

on:
  push:
    releases:
      types:
        - created
    tags:
      - "*"
  workflow_dispatch:

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Luarocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Luarocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          dependencies: |
            nvim-nio
            mimetypes
            xml2lua
            fidget.nvim
          test_dependencies: |
            nlua
          copy_directories: |
            {{ neovim.plugin.dirs }}
