name: Luarocks release

on:
  push:
    releases:
      types:
        - created
    tags:
      - "*"
  workflow_dispatch:

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Luarocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Luarocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          detailed_description: |
            A very fast, powerful, extensible and asynchronous Neovim HTTP client written in Lua.
            rest.nvim by default makes use of its own `curl` wrapper to make requests and a tree-sitter parser to parse http files.
          dependencies: |
            nvim-nio
            mimetypes
            xml2lua
            fidget.nvim
            tree-sitter-http == 0.0.33
          test_dependencies: |
            nlua
          copy_directories: |
            {{ neovim.plugin.dirs }}
